version: "3"

services:
  ipfs:
    build:
      context: ./ipfs
    container_name: ipfs
    restart: always
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    volumes:
      - ./ipfs/.ipfs:/data/ipfs
      - ./build:/build