#!/bin/bash

echo "Publishing..."
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["GET", "POST"]' && ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*", "http://127.0.0.1:8080", "http://localhost:3000", "http://localhost:48084", "https://gateway.ipfs.io", "https://webui.ipfs.io"]'
ipfs add -r -Q /build | ipfs name publish -Q
reboot